name: auto_animated_edited
description: Widgets starting auto play animation when mounted. It is already possible to animate the list and icons.

version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
